// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/hello.ts";
import * as $3 from "./routes/api/ws.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/playground/counter.tsx";
import * as $6 from "./routes/playground/game-of-life.tsx";
import * as $7 from "./routes/playground/github.tsx";
import * as $8 from "./routes/playground/index.tsx";
import * as $9 from "./routes/playground/minesweeper.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/GameOfLifeBoard.tsx";
import * as $$2 from "./islands/Minesweeper.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/hello.ts": $2,
    "./routes/api/ws.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/playground/counter.tsx": $5,
    "./routes/playground/game-of-life.tsx": $6,
    "./routes/playground/github.tsx": $7,
    "./routes/playground/index.tsx": $8,
    "./routes/playground/minesweeper.tsx": $9,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/GameOfLifeBoard.tsx": $$1,
    "./islands/Minesweeper.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
