name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: deno-deploy
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      # - name: Build App
      #   run: deno task build

      - name: Deploy to Deno Deploy
        run: >
          deno install --allow-read --allow-write --allow-env --allow-net --allow-run --no-check -r -f https://deno.land/x/deploy/deployctl.ts;
          deployctl deploy --project=$project $entrypoint --prod
        env: # Or as an environment variable
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
          project: marco # todo: change this to your project name in https://dash.deno.com
          entrypoint: main.ts
